services:
  tagim.api:
    image: tagim.api
    build:
      context: .
      dockerfile: Tagim.Api/Dockerfile
    container_name: tagim_api
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=TagimDb;User Id=postgres;Password=admin;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: tagim_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TagimDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: